name: travel_agencies
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.1.4
  dio: ^5.7.0
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^19.3.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.14
  get_it: ^8.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  internet_connection_checker_plus: ^2.7.1
  logger: ^2.5.0
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  shimmer: ^3.0.0
  timezone: ^0.10.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  permission_handler: ^11.3.1
  go_router: ^16.1.0
  intl_phone_field: ^3.2.0
  pin_code_fields: ^8.0.1



dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter






  flutter_lints: ^5.0.0


flutter:




  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/Cairo/static/
    - assets/
    - assets/svg/
    - assets/fonts/
    - assets/fonts/Cairo/
    - assets/translations/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/static/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/static/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo/static/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo/static/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo/static/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo/static/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo/static/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/Cairo/static/Cairo-ExtraBold.ttf
          weight: 800

























